### ISSUE TITLE
RSI - '0' entered for Total Retail sales is displayed as 'blank'

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/sdx-transform-cs#21]
**Steps**
Launch an RSI 0112 form type enter '0' for Total Retail sales and submit the survey

**Expected:**

All the values entered by the the user must be displayed on the image file.

**Actual:**

Total Retail sales field is displayed as 'Blank' rather then '0' Please find the attached screenshot
![zero missing](https://cloud.githubusercontent.com/assets/21335236/18432642/00ff3854-78db-11e6-8edb-3d02033cec18.png)

**Comment by iwootten** [comment]
This actually seems to be eq passing us a blank value for questions when 0 values are entered. Can the issue be raised there?
