### ISSUE TITLE
SDX: URL entered in comments fields not displayed as expected (PFA)

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/sdx-transform-cs#26]
Expected behaviour

On the image file the URL entered for comments must be displayed clearly

Actual behaviour

URLin the comments field is not displayed as expected. (Please find the attachment)

Steps to reproduce the behaviour

1) Enter all the mandatory information and 
2) enter a lengthy URL into the comments filed
3) submit Survey

Additional information

Issue exits for all the eQ surveys

Browser

Operating System

Screenshot
![sdx_url](https://cloud.githubusercontent.com/assets/21335236/19232298/d96f0bea-8ed6-11e6-95c3-e5186caba337.png)

**Comment by gbanas** [comment]
https://github.com/ONSdigital/sdx-transform-cs/commit/7f7e5441d89173cd52cc5a23a22e391379561d3d was without a description of the fix so I've added it to https://github.com/ONSdigital/sdx-transform-cs/commit/611f4b28460d3c74495dda6cd9bdeaf48b8ed161

**Comment by necrophonic** [comment]
Fixed in release v1.2.0
