### ISSUE TITLE
SDX - 0205 form type does not display 'comments' on the image files

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/sdx-transform-cs#27]
Steps
Launch an 0205 form type enter Values on all the fields and Submit the survey

Expected:

All the values entered by the the user must be displayed on the image file

Actual:

Comments field is missing on the image please find the attached screenshot
![0205_comments](https://cloud.githubusercontent.com/assets/21335236/19275163/bd3f8482-8fca-11e6-8b70-507a524949d6.png)

**Comment by gbanas** [comment]
This is due to missing row label. Can you provide one? For example form 0203 has "Please explain any movements in your data e.g. sale held, branches opened or sold, extreme weather, or temporary closure of shop".

**Comment by ajmaddaford** [comment]
@gbanas 0205 uses the same label as 0203

**Comment by gbanas** [comment]
I have requested a pull request https://github.com/ONSdigital/sdx-transform-cs/pull/30 which contains a fix for this issue.
